### ISSUE TITLE
worth promoting?

### ISSUE THREAD

**Issue by LauriZalando** [zalando/spin-docker-selenium#1]
Hey, this seems like it could be potentially useful to the broader community, but it needs a second maintainer and a bit more documentation. Thoughts on its potential?

**Comment by elgalu** [comment]
I added @pfigue as maintainer through https://github.com/zalando/spin-docker-selenium/commit/68453d2eec1fca4d4280ba407972416cf4bbf3dd

This repo is a fairly simple script to use a shared machine as a Selenium grid for a team of people for example, it might be useful.

**Comment by LappleApple** [comment]
Can we chat about it for five minutes? Would like to know if anything similar exists, or if this is similar to something but solves a problem faster/easier/better. Let's see if there's a good hook here.

**Comment by elgalu** [comment]
Your concern made me realize this repo is not the best way to achieve the purpose, I think orchestration through https://github.com/docker/compose is the way to go instead of this bash scripting.

**Comment by LappleApple** [comment]
thanks!
